export const GET_IMAGE_PRODUCT_REQUEST = "GET_IMAGE_PRODUCT_REQUEST ";
export const GET_IMAGE_PRODUCT_SUCCESS = "GET_IMAGE_PRODUCT_SUCCESS";
export const GET_IMAGE_PRODUCT_FAILURE = "GET_IMAGE_PRODUCT_FAILURE";

export const UPDATE_IMAGE_PRODUCT_REQUEST = "UPDATE_IMAGE_PRODUCT_REQUEST";
export const UPDATE_IMAGE_PRODUCT_SUCCESS = "UPDATE_IMAGE_PRODUCT_SUCCESS";
export const UPDATE_IMAGE_PRODUCT_FAILURE = "UPDATE_IMAGE_PRODUCT_FAILURE";