export const GET_IMPORT_WARE_HOUSE_REQUEST = "GET_IMPORT_WARE_HOUSE_REQUEST";
export const GET_IMPORT_WARE_HOUSE_SUCCESS = "GET_IMPORT_WARE_HOUSE_SUCCESS";
export const GET_IMPORT_WARE_HOUSE_FAILURE = "GET_IMPORT_WARE_HOUSE_FAILURE";

export const SEARCH_IMPORT_WARE_HOUSE_REQUEST = "SEARCH_IMPORT_WARE_HOUSE_REQUEST";
export const SEARCH_IMPORT_WARE_HOUSE_SUCCESS = "SEARCH_IMPORT_WARE_HOUSE_SUCCESS";
export const SEARCH_IMPORT_WARE_HOUSE_FAILURE = "SEARCH_IMPORT_WARE_HOUSE_FAILURE";