export const ADD_IMPORT_WARE_HOUSE_REQUEST = "ADD_IMPORT_WARE_HOUSE_REQUEST ";
export const ADD_IMPORT_WARE_HOUSE_SUCCESS = "ADD_IMPORT_WARE_HOUSE_SUCCESS";
export const ADD_IMPORT_WARE_HOUSE_FAILURE = "ADD_IMPORT_WARE_HOUSE_FAILURE";