export const GET_LIST_ORDER_REQUEST = "GET_LIST_ORDER_REQUEST";
export const GET_LIST_ORDER_SUCCESS = "GET_LIST_ORDER_SUCCESS";
export const GET_LIST_ORDER_FAILURE = "GET_LIST_ORDER_FAILURE";

export const SEARCH_LIST_ORDER_REQUEST = 'SEARCH_LIST_ORDER_REQUEST'
export const SEARCH_LIST_ORDER_SUCCESS = 'SEARCH_LIST_ORDER_SUCCESS'
export const SEARCH_LIST_ORDER_FAILURE = 'SEARCH_LIST_ORDER_FAILURE'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'