export const UPDATE_PRODUCT_PRICE_REQUEST = 'UPDATE_PRODUCT_PRICE_REQUEST';
export const UPDATE_PRODUCT_PRICE_SUCCESS = 'UPDATE_PRODUCT_PRICE_SUCCESS';
export const UPDATE_PRODUCT_PRICE_FAILURE = 'UPDATE_PRODUCT_PRICE_FAILURE';

export const ADD_ITEM_PRODUCT_REQUEST = 'ADD_ITEM_PRODUCT_REQUEST';
export const ADD_ITEM_PRODUCT_SUCCESS = 'ADD_ITEM_PRODUCT_SUCCESS';
export const ADD_ITEM_PRODUCT_FAILURE = 'ADD_ITEM_PRODUCT_FAILURE';

export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_FAILURE = 'GET_LIST_PRODUCT_FAILURE';

export const SEARCH_LIST_PRODUCT_REQUEST = 'SEARCH_LIST_PRODUCT_REQUEST';
export const SEARCH_LIST_PRODUCT_SUCCESS = 'SEARCH_LIST_PRODUCT_SUCCESS';
export const SEARCH_LIST_PRODUCT_FAILURE = 'SEARCH_LIST_PRODUCT_FAILURE';

export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";