export const SEARCH_LIST_ORDER_REQUEST = 'SEARCH_LIST_ORDER_REQUEST'
export const SEARCH_LIST_ORDER_SUCCESS = 'SEARCH_LIST_ORDER_SUCCESS'
export const SEARCH_LIST_ORDER_FAILURE = 'SEARCH_LIST_ORDER_FAILURE'