export const SEARCH_WARE_HOUSE_REQUEST  = 'SEARCH_WARE_HOUSE_REQUEST';
export const SEARCH_WARE_HOUSE_SUCCESS  = 'SEARCH_WARE_HOUSE_SUCCESS';
export const SEARCH_WARE_HOUSE_FAILURE  = 'SEARCH_WARE_HOUSE_FAILURE';