export const GET_WARE_HOUSE_REQUEST = "GET_WARE_HOUSE_REQUEST";
export const GET_WARE_HOUSE_SUCCESS = "GET_WARE_HOUSE_SUCCESS";
export const GET_WARE_HOUSE_FAILURE = "GET_WARE_HOUSE_FAILURE";

export const SEARCH_WARE_HOUSE_REQUEST = "SEARCH_WARE_HOUSE_REQUEST";
export const SEARCH_WARE_HOUSE_SUCCESS = "SEARCH_WARE_HOUSE_SUCCESS ";
export const SEARCH_WARE_HOUSE_FAILURE = "SEARCH_WARE_HOUSE_FAILURE";
