export const listProductData = {
  listProduct: [
    {
      id: "1",
      name: "ROSTOR 20mg",
      quantity: "8/10",
      description: "Viên Nang, Uống",
      rootPrice: "3",
      floorPrice: "4",
      expiry: "4/2024",
      updateUt: "",
      unit: "$",
      suppl:
        "Tăng cholesterol máu nguyên phát (loại IIa kể cả tăng cholesterol máu gia đình kiểu dị hợp tử) hoặc rối loạn lipid máu hỗn hợp (loại IIb). Tăng cholesterol máu gia đình kiểu đồng hợp tử.",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/116983-5541.jpg",
      codeProduct: "RO20",
      phoneNumber: "345678765",
    },

    {
      id: "2",
      name: "Tatanol",
      quantity: "7/10",
      description:
        " Làm giảm các cơn đau do cảm cúm, nhức đầu, đau họng, đau nhức cơ xương, đau do hành kinh, đau răng, đau nửa đầu. Hạ sốt. Phối hợp trong điều trị nguyên nhân gây đau hoặc sốt.",
      rootPrice: "1",
      floorPrice: "2",
      expiry: "7/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/98038-5542.jpg",
      codeProduct: "TN",
      phoneNumber: "12345",
    },

    {
      id: "3",
      name: "Fluzinstad",
      quantity: "8/10",
      description:
        "Fluzinstad 5 thuộc phân nhóm thuốc trị đau nửa đầu. Thành phần của loại thuốc này là flunarizin (dihydroclorid) 5mg, tá dược vừa đủ 1 viên.",
      rootPrice: "5",
      floorPrice: "4",
      expiry: "2/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty TNHH LD Stada - Việt Nam.",
      avatar:
        "https://thongtinthuoc.com.vn/uploads/bietduoc/Bao/VD-11963-10%20(1)_ex.jpg",
      codeProduct: "FS",
      phoneNumber: "4532165",
    },

    {
      id: "4",
      name: "COLDFLU Forte",
      quantity: "8/10",
      description:
        "Thuốc được chỉ định làm giảm các triệu chứng: nghẹt mũi, chảy nước mũi, chảy nước mắt, ngứa mắt, viêm xoang kèm ho và sốt (hoặc nhức đầu, đau nhức bắp thịt) trong cảm cúm.",
      rootPrice: "4",
      floorPrice: "4",
      expiry: "4/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/116987-5545.jpg",
      codeProduct: "CF",
      phoneNumber: "348765",
    },

    {
      id: "5",
      name: "Pyme DIAPRO MR",
      quantity: "9/10",
      description: "Đái tháo đường type 2 không phụ thuộc insulin ở người lớn.",
      rootPrice: "7",
      floorPrice: "8",
      expiry: "10/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/116984-5544.jpg",
      codeProduct: "PDM",
      phoneNumber: "9068421",
    },

    {
      id: "6",
      name: "pms-BACTAMOX 1g",
      quantity: "8/10",
      description:
        "Thuốc ít gây ra tai biến, vì được dung nạp tốt ngay cả ở liều cao. Những phản ứng cấp xảy ra phụ thuộc vào tình trạng quá mẫn của từng cá thể. Trong trường hợp dùng quá liều, ngưng dùng thuốc ngay và sử dụng các biện pháp hỗ trợ, có thể gây nôn, rửa dạ dày nếu mới quá liều. Không có thuốc giải độc đặc hiệu. Amoxicillin và Sulbactam có thể được loại bỏ bằng thẩm phân máu.",
      rootPrice: "10",
      floorPrice: "9",
      expiry: "10/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/116988-5554.png",
      codeProduct: "PB01",
      phoneNumber: "19387456545",
    },

    {
      id: "7",
      name: "pms - Claminat 625 mg",
      quantity: "9/10",
      description:
        "Thuốc ít gây ra tai biến, vì được dung nạp tốt ngay cả ở liều cao. Những phản ứng cấp xảy ra phụ thuộc vào tình trạng quá mẫn của từng cá thể. Nguy cơ chắc chắn là tăng kali huyết khi dùng liều rất cao vì Acid clavulanic được dùng dưới dạng muối kali.",
      rootPrice: "6",
      floorPrice: "5",
      expiry: "6/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/82788-5626.png",
      codeProduct: "PC625",
      phoneNumber: "39247393",
    },

    {
      id: "8",
      name: "Zobacta_UL 4,5g",
      quantity: "6/10",
      description:
        "Nhiểm khuẩn nặng, nhiễm khuẩn máu và nhiễm khuẩn đường tiết niệu có biến chứng do các vi khuẩn nhạy cảm, đặc biệt là do Pseudomonas.",
      rootPrice: "5",
      floorPrice: "4",
      expiry: "7/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar: "https://yduoc-media.s3.amazonaws.com/bietduoc/102178-5553.png",
      codeProduct: "ZU4.5",
      phoneNumber: "39410320329",
    },
    {
      id: "9",
      name: "pms-Probio",
      quantity: "9/10",
      description:
        "Cân bằng hệ vi sinh đường ruột bị phá vỡ do: rượu, stress, nhiễm trùng, sử dụng kháng sinh hoặc các thuốc hoá trị liệu.",
      rootPrice: "9",
      floorPrice: "8",
      expiry: "12/2024",
      updateUt: "",
      unit: "$",
      suppl: "Uống",
      origin: "Công ty Cổ phần Pymepharco",
      avatar:
        "https://cdn.tgdd.vn/Products/Images/12098/131584/thuoc-com-pms-probio-mac-dinh-2.jpg",
      codeProduct: "PP",
      phoneNumber: "943240352",
    },
  ],
  key: "list-product",
};
